version: "3.7"
services: 
  mysql-db:
    container_name: mydb2
    build:
      context: ./db
    image: alensu0829/mysql-db-02
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      my-bridge-001:
    volumes:
      - db-data:/var/lib/mysql
  java-app:
    container_name: myapp2
    build:
      context: ./app
    image: alensu0829/java-app-02
    ports:
      - "8080:8080"
    command: ./wait-for-it.sh mydb:3306 -- java -jar target/springboot-mall-0.0.1-SNAPSHOT.jar 
    environment:
      - DB_HOST_IP=mydb
    networks:
      my-bridge-001:


networks:
  my-bridge-001:

volumes:
  db-data:

